export { default as Home } from "./home/Home"
export { default as Adding } from "./adding/Adding"
export { default as Ad } from "./ad/Ad"
export { default as InfoAd } from "../components/info-ad/Info-ad"
export { default as Admin } from "../components/admin/Admin"
export { default as UserProfile } from "../components/user-profile/User-profile"
export { default as Catalog } from "../components/catalog/Catalog"
export {default as Layout } from "../components/layout/Layout"